[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
prediction_game = "7sBHvSPH2BaNhTEk9nMWyhEwYttbrvC458RLrR4X3rqw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/canfly/.config/solana/cli/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
